### ISSUE TITLE
Admin repozytorium

### ISSUE THREAD

**Issue by rudnickirobert** [KWZP/Projekt#11]
prośba o nadanie mi praw administratora do repozytorium

**Comment by DamianSzczesniak** [comment]
Z tego co przeczytałem nie ma takiej możliwości, w repo przypisanym do osoby istnieje tylko owner i collabolators.

**Comment by rudnickirobert** [comment]
w ustawieniach repozytorium proszę zmienić właściciela na organization KWZP

**Comment by DamianSzczesniak** [comment]
Zrobione
