### ISSUE TITLE
 new KWZP_PROJEKTEntities();

### ISSUE THREAD

**Issue by rudnickirobert** [KWZP/Projekt#17]
W aplikacji powinno być tylko jedno miejsce gdzie inicjalizujemy obiekt typu KWZP_PROJEKTEntities. Inne formularze mają korzystać z instancji utworzonej np w formularzu startowym.

**Comment by DamianSzczesniak** [comment]
Proszę o adekwatną poprawę w we wszystkich modułach. Gdy któraś grupa poprawi proszę dać znać tu, jak wszyscy zrobią, zamknę.

**Comment by PiotrStrozekWAT** [comment]
Na ile dobrze rozumiem dany issue, to formularze Kadr odwołują się do obiektu KWZP_PROJEKTEntites db; z formularza Form1 i tylko tam jest on inicjowany jako new.

**Comment by DamianSzczesniak** [comment]
LOGISTYKA POPRAWIONA

**Comment by DamianSzczesniak** [comment]
Produkcja również się stosuje.
