### ISSUE TITLE
Problem z dodaniem odpowiedniego pracownika

### ISSUE THREAD

**Issue by KamilRajkowski** [KWZP/Projekt#41]
Dzień dobry,

czy może Pan spojrzeć na ostatniego pusha z brancha produkcjaostatnieformularze? Mam problem z dodaniem wybranego pracownika i po godzinie wybierania różnych opcji skończyły mi się pomysły. Prawdopodobnie jest to spowodowane tym, że są 2 gridView ale nie jestem pewien. Zawsze dodaje się ten sam pracownik nie zależnie co zaznaczę na gridView.

Z góry dziękuję za pomoc,
Kamil Rajkowski

**Comment by KamilRajkowski** [comment]
Po konsultacji z Piotrkiem doszliśmy do wniosku, że dane do bazy danych są wpisywane dobrze i kwerenda w bazie danych wyświetla je dobrze natomiast linijka:

pRACOWNICYWPRACYBindingSource.DataSource = db.PRACOWNICY_W_PRACY.Where(x => x.DATA_DZIEN == data).ToList(); 

wybiera wszystkie elementy z kwerendy z datą równą dacie dzisiejszej i zapisuje je w kwerendzie ale daje elementom listy wartości równe pierwszemu elementowi w kwerendzie. Nie wiem dlaczego tak się dzieje i póki co nie mogę tego naprawić.

**Comment by DamianSzczesniak** [comment]
Sprawdźcie klucze podstawowe tej kwerendy w modelu entity

**Comment by KamilRajkowski** [comment]
Dobra działa

**Comment by rudnickirobert** [comment]
nawet nie zdążyłem zareagować ;)
