### ISSUE TITLE
zakomentowane CREATE VIEW

### ISSUE THREAD

**Issue by rudnickirobert** [KWZP/Projekt#6]
Dlaczego to jest zakomentowane? Z założenia skrypt bazy ma ją tworzyć- nie komentujemy żadnego DDL. Proszę poprawić dla wszystkich widoków

https://github.com/DamianSzczesniak/Projekt/blob/8d3143e48e3b0aa2824c5d8964fd82716cbb0c13/KWZP_PROJECT_DATABASE_CREATOR.sql#L789

**Comment by DamianSzczesniak** [comment]
Poprawione
